/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "background": "#f7f9fb",
              "on-tertiary-container": "#98805d",
              "on-primary": "#ffffff",
              "tertiary-fixed-dim": "#dec29a",
              "error": "#ba1a1a",
              "error-container": "#ffdad6",
              "on-secondary-container": "#54647a",
              "surface-bright": "#f7f9fb",
              "outline": "#76777d",
              "on-secondary-fixed": "#0b1c30",
              "on-background": "#191c1e",
              "on-tertiary-fixed-variant": "#574425",
              "secondary-container": "#d0e1fb",
              "primary": "#000000",
              "surface-tint": "#565e74",
              "surface-variant": "#e0e3e5",
              "tertiary-fixed": "#fcdeb5",
              "inverse-on-surface": "#eff1f3",
              "surface-container-high": "#e6e8ea",
              "on-error": "#ffffff",
              "primary-fixed-dim": "#bec6e0",
              "on-primary-fixed": "#131b2e",
              "secondary-fixed-dim": "#b7c8e1",
              "on-primary-container": "#7c839b",
              "on-tertiary": "#ffffff",
              "primary-fixed": "#dae2fd",
              "surface": "#f7f9fb",
              "on-tertiary-fixed": "#271901",
              "secondary": "#505f76",
              "surface-container": "#eceef0",
              "on-secondary-fixed-variant": "#38485d",
              "inverse-surface": "#2d3133",
              "secondary-fixed": "#d3e4fe",
              "inverse-primary": "#bec6e0",
              "on-surface": "#191c1e",
              "tertiary-container": "#271901",
              "surface-container-lowest": "#ffffff",
              "surface-container-highest": "#e0e3e5",
              "surface-dim": "#d8dadc",
              "tertiary": "#000000",
              "on-primary-fixed-variant": "#3f465c",
              "on-error-container": "#93000a",
              "outline-variant": "#c6c6cd",
              "on-secondary": "#ffffff",
              "surface-container-low": "#f2f4f6",
              "primary-container": "#131b2e",
              "on-surface-variant": "#45464d"
          },
          "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
          },
          "spacing": {
              "max-width": "1440px",
              "gutter": "24px",
              "section-gap": "64px",
              "container-padding": "32px",
              "base": "8px"
          },
          "fontFamily": {
              "headline-md": ["Hanken Grotesk"],
              "body-md": ["Inter"],
              "display-lg": ["Hanken Grotesk"],
              "data-mono": ["JetBrains Mono"],
              "body-lg": ["Inter"],
              "body-sm": ["Inter"],
              "label-caps": ["JetBrains Mono"],
              "headline-sm": ["Hanken Grotesk"]
          },
          "fontSize": {
              "headline-md": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "500" }],
              "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
              "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
              "data-mono": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
              "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
              "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
              "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500" }],
              "headline-sm": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }]
          }
      }
  },
  plugins: [],
}
